# Generated by Django 4.2.11 on 2025-07-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurpersonnaliser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
