# Generated by Django 4.2.11 on 2025-07-28 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ami',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_envoyees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ami',
            name='receveur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ami',
            unique_together={('demandeur', 'receveur')},
        ),
    ]
