# Generated by Django 4.2.11 on 2025-08-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('reaction', 'Réaction'), ('comment', 'Commentaire'), ('friend_request', 'Demande d’ami'), ('friend_accept', 'Demande d’ami acceptée'), ('share', 'Partage')], max_length=50),
        ),
    ]
